services:
  db:
    image: postgres:15.3
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: quantum
      POSTGRES_USER: quantum
      POSTGRES_DB: quantum
    ports:
      - "5432:5432"
